### ISSUE TITLE
StoredProcedures - Exec issue

### ISSUE THREAD

**Issue by anoopk6** [bmizerany/pq#6]
Stored procedure invoked using conn.Exec("SELECT sp(....)") is failing with error 'pq: unknown response for simple query: 'D'. 'It is working if conn.Query is used. 

With Exec subsequent queries (eg SELECT 1) on same connections are failing with errors like
- pq: unexpected describe rows response: 'C'
- pq: unexpected bind response: '1'

'D' seems to indicate a data row. Exec can be used for queries like 'INSERT ... RETURNING id'  So shouldn't 'D' be handled for Exec case ?

**Comment by bmizerany** [comment]
Closing. Please re-post at http://github.com/lib/pq if there is still a problem.
