### ISSUE TITLE
Support SetMaxIdleConns

### ISSUE THREAD

**Issue by izaurio** [bmizerany/pq#8]
```
db, err := sql.Open("...")
db.SetMaxIdleConns(12)


Error: db.SetMaxIdleConns undefined (type *sql.DB has no field or method SetMaxIdleConns)
```

Be able to implement it?

**Comment by fdr** [comment]
That would be wonderful.  I think it's backwards compatible with older Gos, too.  @deafbybeheading may be interested.

**Comment by msakrejda** [comment]
Looks like this is Go 1.1 (not to mention that it's of limited usefulness if it only caps max _idle_ connections).

But we could introduce version-dependent tags:

> When checking out or updating a package, get looks for a branch or tag that matches the locally installed version of Go. The most important rule is that if the local installation is running version "go1", get searches for a branch or tag named "go1". If no such version exists it retrieves the most recent version of the package. 

(see [here](http://golang.org/cmd/go/))

**Comment by bmizerany** [comment]
Closing. Please re-post at http://github.com/lib/pq if there is still a problem.
