### ISSUE TITLE
Support for bulk imports with COPY FROM STDIN

### ISSUE THREAD

**Issue by olt** [bmizerany/pq#9]
PostgreSQL's COPY FROM STDIN is much faster for bulk imports (8x in my tests). 

It's a bit tricky to implement it with the existing database.sql API, but I think I found a reasonable solution. You can see it here in action: https://github.com/olt/pq/blob/bulk/copy_test.go

The only wart is that sql.Stmt.Close() doesn't pass the errors from the COPY stmt.Close(). You need to call .Exec() without arguments before .Close() to synchronize and get any errors for the otherwise asynchronous inserts. (Don't know if this is a bug in Go and worth reporting?)

What do you think? I could write a bit documentation for it and send a pull request.

**Comment by bmizerany** [comment]
Closing. Please re-post at http://github.com/lib/pq if there is still a problem.
